//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLavacar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdlavacarEntities : DbContext
    {
        public bdlavacarEntities()
            : base("name=bdlavacarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Canton> Canton { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Tbl_MarcaVehiculo_MV> Tbl_MarcaVehiculo_MV { get; set; }
        public DbSet<Tbl_PaisFabricacion_PF> Tbl_PaisFabricacion_PF { get; set; }
        public DbSet<Tbl_Persona_P> Tbl_Persona_P { get; set; }
        public DbSet<Tbl_Seguridad_SG> Tbl_Seguridad_SG { get; set; }
        public DbSet<Tbl_Servicio_S> Tbl_Servicio_S { get; set; }
        public DbSet<Tbl_Tipo_TV> Tbl_Tipo_TV { get; set; }
        public DbSet<Tbl_TipoPersona_TP> Tbl_TipoPersona_TP { get; set; }
        public DbSet<Tbl_Vehiculo_V> Tbl_Vehiculo_V { get; set; }
        public DbSet<TblFactura_F> TblFactura_F { get; set; }
        public DbSet<Tbl_FacturaServicioVehiculo_FSV> Tbl_FacturaServicioVehiculo_FSV { get; set; }
    }
}
