//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLavacar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Servicio_S
    {
        public Tbl_Servicio_S()
        {
            this.Tbl_FacturaServicioVehiculo_FSV = new HashSet<Tbl_FacturaServicioVehiculo_FSV>();
        }
    
        public int Id_Servicio_S { get; set; }
        public string Descripcion_S { get; set; }
        public int Precio_S { get; set; }
        public string Tipo_S { get; set; }
    
        public virtual ICollection<Tbl_FacturaServicioVehiculo_FSV> Tbl_FacturaServicioVehiculo_FSV { get; set; }
    }
}
