//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLavacar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Seguridad_SG
    {
        public int Id_Usuarios_SG { get; set; }
        public string Usuario_SG { get; set; }
        public string Contraseña_SG { get; set; }
        public int Id_Cliente_SG { get; set; }
        public System.DateTime UltimaFecha_SG { get; set; }
    
        public virtual Tbl_Persona_P Tbl_Persona_P { get; set; }
    }
}
