//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLavacar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Persona_P
    {
        public Tbl_Persona_P()
        {
            this.Tbl_Seguridad_SG = new HashSet<Tbl_Seguridad_SG>();
            this.TblFactura_F = new HashSet<TblFactura_F>();
            this.Tbl_Vehiculo_V = new HashSet<Tbl_Vehiculo_V>();
        }
    
        public int Id_Cliente_P { get; set; }
        public int Cedula_P { get; set; }
        public string Genero_P { get; set; }
        public System.DateTime Fecha_Nacimiento_P { get; set; }
        public string Nombre_P { get; set; }
        public string Correo_P { get; set; }
        public int Id_Provincia_P { get; set; }
        public int Id_Canton_P { get; set; }
        public int Id_Tipo_P { get; set; }
        public int Id_Distrito_P { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Tbl_TipoPersona_TP Tbl_TipoPersona_TP { get; set; }
        public virtual ICollection<Tbl_Seguridad_SG> Tbl_Seguridad_SG { get; set; }
        public virtual ICollection<TblFactura_F> TblFactura_F { get; set; }
        public virtual ICollection<Tbl_Vehiculo_V> Tbl_Vehiculo_V { get; set; }
    }
}
