//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLavacar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactura_F
    {
        public TblFactura_F()
        {
            this.Tbl_FacturaServicioVehiculo_FSV = new HashSet<Tbl_FacturaServicioVehiculo_FSV>();
        }
    
        public int Id_Factura_F { get; set; }
        public Nullable<int> Id_Vehiculo_F { get; set; }
        public int Id_Persona_F { get; set; }
        public string Total_F { get; set; }
        public System.DateTime Fecha_F { get; set; }
    
        public virtual Tbl_Persona_P Tbl_Persona_P { get; set; }
        public virtual Tbl_Vehiculo_V Tbl_Vehiculo_V { get; set; }
        public virtual ICollection<Tbl_FacturaServicioVehiculo_FSV> Tbl_FacturaServicioVehiculo_FSV { get; set; }
    }
}
