
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BDLavacar.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Vehiculo_V
{

    public Tbl_Vehiculo_V()
    {

        this.TblFactura_F = new HashSet<TblFactura_F>();

        this.Tbl_Persona_P = new HashSet<Tbl_Persona_P>();

    }


    public int Id_Vehiculo_V { get; set; }

    public string Placa_V { get; set; }

    public int Id_Marca_V { get; set; }

    public int Id_Tipo_V { get; set; }

    public int Numero_Puertas_V { get; set; }

    public int Numero_Ruedas_V { get; set; }



    public virtual Tbl_MarcaVehiculo_MV Tbl_MarcaVehiculo_MV { get; set; }

    public virtual Tbl_Tipo_TV Tbl_Tipo_TV { get; set; }

    public virtual ICollection<TblFactura_F> TblFactura_F { get; set; }

    public virtual ICollection<Tbl_Persona_P> Tbl_Persona_P { get; set; }

}

}
